### ISSUE TITLE
no-dangling-commas

### ISSUE THREAD

**Issue by philsturgeon** [dseguy/clearPHP#8]
This is just bad advice.

1.) Indentation here is messed up.

``` php
$array = array('a', 
                  'b',
                 );
$array2 = ['c', 
             'd',
            ];
```

What is going on there? :)

2.) You have a copy paste error in `The following pattern is considered legit:`

```
$array = array('a', 
                  'b'
                 );

$array2 = ['c', 'd', ];
```

I guess that `$array2` was supposed to have the `,` removed?

Either way, trailing commas on multi-line array definitions are awesome. They are also supported in pretty much every language I've used, but are banned in JSON.

They are a style guide choice for sure, but a) they don't hurt at all, and b) they reduce friction and potential conflicts in diffs. I've seen a LOT of conflicts caused by just this, and since asking developers on various teams to use trailing diffs those problems have gone away.

I'd like to see this one deleted entirely.

**Comment by evantishuk** [comment]
I am in agreement with @philsturgeon. While strictness is generally admirable, it's decidedly lame in this situation. Trailing commas don't degrade the readability of code whatsoever. A stricter policy only creates unnecessary obstacles and gotchas. I routinely thank PHP's syntax when I can effortlessly copy or re-order lines of key/val pairs without having to worry about that trailing comma. When I have to switch to coding in JS I curse it's strict nature.

**Comment by dseguy** [comment]
Changing all arrays to remove them is futile : I'd classify this as coding convention, rather than less bug-prone code.  

Out of 200 PHP projects, a very small minority followed this. 

I don't like that rule too much myself. :)

**Comment by philsturgeon** [comment]
So remove it! :+1:

**Comment by auroraeosrose** [comment]
I'm +1ing the "Remove it" - this is exactly the OPPOSITE of most coding standards and against the advice I give people when coding in PHP - it's far less error prone to always have a trailing comma after array entries - causes fewer merge conflicts and far fewer parse errors when you add/remove entries :)

**Comment by weierophinney** [comment]
A clarification to the comment from @philsturgeon — the most compelling reason I've seen stated for keeping the trailing comma on multi-line array definitions is for simplifying diffs associated with version control. Essentially, adding or removing an array entry only changes that line, and no others; if you require that the last entry MUST NOT have a comma, then:
- removing the last entry ALWAYS results in a two-line diff, as the previous line must now change to remove the comma
- adding a new entry at the end ALWAYS results in a two-line diff, as the former last entry now must add a comma
- re-ordering that involves the last entry ALWAYS results in N+1 lines of diff (again, because whatever the new last entry is must also remove the comma)

Essentially, trailing commas simplify diffs and reduce merge conflicts. I only wish JavaScript allowed it! (I've become so accustomed to doing it in PHP that I've introduced errors in my JavaScript and JSON by keeping the trailing commas!)

**Comment by philsturgeon** [comment]
>  (I've become so accustomed to doing it in PHP that I've introduced errors in my JavaScript and JSON by keeping the trailing commas!)

Real problem.

**Comment by dragoonis** [comment]
Trailing commas for the win :+1:

**Comment by jrfnl** [comment]
+1 on trailing comma's, aka removing this rule.
It helps prevents parse errors from copy/paste actions, so should be considered a _good thing‎™‎_

**Comment by dseguy** [comment]
OK. Rule removed.
